# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - HTML_DJLINT
  - REPOSITORY_TRIVY
DISABLE_ERRORS: true
VALIDATE_ALL_CODEBASE: false
