# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
  - EDITORCONFIG
  - HTML
  - REPOSITORY
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - HTML_DJLINT
  - REPOSITORY_TRIVY
DISABLE_ERRORS: true
VALIDATE_ALL_CODEBASE: false
# DISABLE:
#   - CLOUDFORMATION
#   # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
#   - CSS
#   - EDITORCONFIG
#   # - SPELL # Uncomment to disable checks of spelling mistakes
#   - JAVASCRIPT
#   - TEKTON
# DISABLE_LINTERS:
#   - JSON_PRETTIER
#   - MARKDOWN_MARKDOWN_LINK_CHECK
#   - PYTHON_PYRIGHT
#   - REPOSITORY_GITLEAKS
#   - REPOSITORY_KICS
#   - SPELL_PROSELINT
#   - SPELL_MISSPELL
#   - SPELL_VALE
# DISABLE_ERRORS_LINTERS:
#   - PYTHON_BANDIT
#   - REPOSITORY_DEVSKIM
#   - REPOSITORY_GRYPE
#   - REPOSITORY_SEMGREP
#   - REPOSITORY_TRUFFLEHOG
#   - SPELL_LYCHEE
